// Generated by https://quicktype.io

export interface JSONProductos {
    productos: dataProducto[];
}

export interface dataProducto { 
    id:          number;
    nombre:      string;
    descripcion: string;
    img:         string;
    precio:      number;
    precio2:      number;
    precio3:      number;
    marca:       number;
    stock: number;
}
